services:
  - type: web
    name: pert-backend
    env: docker
    rootDir: backend-pert
    dockerfilePath: ./Dockerfile
    plan: free
    disk:
      name: pert-json-storage
      mountPath: /var/www/html/storage/app/data
      sizeGB: 1
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://pert-backend.onrender.com
      - key: APP_KEY
        sync: false
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file