services:
  - type: web
    name: pert-backend
    env: docker
    rootDir: backend-pert
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://pert-backend.onrender.com
      - key: APP_KEY
        sync: false
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: array